/**
 * style-api
 * This is a API document for Stylens Service
 *
 * OpenAPI spec version: 0.0.2
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetObjectsByImageIdResponse', 'model/GetObjectsResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GetObjectsByImageIdResponse'), require('../model/GetObjectsResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.StyleApi) {
      root.StyleApi = {};
    }
    root.StyleApi.ObjectApi = factory(root.StyleApi.ApiClient, root.StyleApi.GetObjectsByImageIdResponse, root.StyleApi.GetObjectsResponse);
  }
}(this, function(ApiClient, GetObjectsByImageIdResponse, GetObjectsResponse) {
  'use strict';

  /**
   * Object service.
   * @module api/ObjectApi
   * @version 0.0.2
   */

  /**
   * Constructs a new ObjectApi. 
   * @alias module:api/ObjectApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getObjectsByImageId operation.
     * @callback module:api/ObjectApi~getObjectsByImageIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetObjectsByImageIdResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Query to search multiple objects
     * 
     * @param {String} imageId 
     * @param {module:api/ObjectApi~getObjectsByImageIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetObjectsByImageIdResponse}
     */
    this.getObjectsByImageId = function(imageId, callback) {
      var postBody = null;

      // verify the required parameter 'imageId' is set
      if (imageId === undefined || imageId === null) {
        throw new Error("Missing the required parameter 'imageId' when calling getObjectsByImageId");
      }


      var pathParams = {
        'imageId': imageId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = GetObjectsByImageIdResponse;

      return this.apiClient.callApi(
        '/objects/images/{imageId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getObjectsByUserImageFile operation.
     * @callback module:api/ObjectApi~getObjectsByUserImageFileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetObjectsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Query to search objects and images
     * 
     * @param {File} file User&#39;s Image file to upload (only support jpg format yet)
     * @param {module:api/ObjectApi~getObjectsByUserImageFileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetObjectsResponse}
     */
    this.getObjectsByUserImageFile = function(file, callback) {
      var postBody = null;

      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling getObjectsByUserImageFile");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'file': file
      };

      var authNames = [];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['application/json'];
      var returnType = GetObjectsResponse;

      return this.apiClient.callApi(
        '/objects', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
