/**
 * style-api
 * This is a API document for Stylens Service
 *
 * OpenAPI spec version: 0.0.2
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StyleApi) {
      root.StyleApi = {};
    }
    root.StyleApi.Box = factory(root.StyleApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Box model module.
   * @module model/Box
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>Box</code>.
   * @alias module:model/Box
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Box</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Box} obj Optional instance to populate.
   * @return {module:model/Box} The populated <code>Box</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('left')) {
        obj['left'] = ApiClient.convertToType(data['left'], 'Number');
      }
      if (data.hasOwnProperty('right')) {
        obj['right'] = ApiClient.convertToType(data['right'], 'Number');
      }
      if (data.hasOwnProperty('top')) {
        obj['top'] = ApiClient.convertToType(data['top'], 'Number');
      }
      if (data.hasOwnProperty('bottom')) {
        obj['bottom'] = ApiClient.convertToType(data['bottom'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} left
   */
  exports.prototype['left'] = undefined;
  /**
   * @member {Number} right
   */
  exports.prototype['right'] = undefined;
  /**
   * @member {Number} top
   */
  exports.prototype['top'] = undefined;
  /**
   * @member {Number} bottom
   */
  exports.prototype['bottom'] = undefined;



  return exports;
}));


