/**
 * style-api
 * This is a API document for Stylens Service
 *
 * OpenAPI spec version: 0.0.2
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Box', 'model/Image'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Box'), require('./Image'));
  } else {
    // Browser globals (root is window)
    if (!root.StyleApi) {
      root.StyleApi = {};
    }
    root.StyleApi.BoxObject = factory(root.StyleApi.ApiClient, root.StyleApi.Box, root.StyleApi.Image);
  }
}(this, function(ApiClient, Box, Image) {
  'use strict';




  /**
   * The BoxObject model module.
   * @module model/BoxObject
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>BoxObject</code>.
   * @alias module:model/BoxObject
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>BoxObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BoxObject} obj Optional instance to populate.
   * @return {module:model/BoxObject} The populated <code>BoxObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('box')) {
        obj['box'] = Box.constructFromObject(data['box']);
      }
      if (data.hasOwnProperty('image_id')) {
        obj['image_id'] = ApiClient.convertToType(data['image_id'], 'String');
      }
      if (data.hasOwnProperty('version_id')) {
        obj['version_id'] = ApiClient.convertToType(data['version_id'], 'String');
      }
      if (data.hasOwnProperty('class_code')) {
        obj['class_code'] = ApiClient.convertToType(data['class_code'], 'String');
      }
      if (data.hasOwnProperty('score')) {
        obj['score'] = ApiClient.convertToType(data['score'], 'Number');
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], [Image]);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/Box} box
   */
  exports.prototype['box'] = undefined;
  /**
   * @member {String} image_id
   */
  exports.prototype['image_id'] = undefined;
  /**
   * @member {String} version_id
   */
  exports.prototype['version_id'] = undefined;
  /**
   * @member {String} class_code
   */
  exports.prototype['class_code'] = undefined;
  /**
   * @member {Number} score
   */
  exports.prototype['score'] = undefined;
  /**
   * @member {Array.<module:model/Image>} images
   */
  exports.prototype['images'] = undefined;



  return exports;
}));


