/**
 * style-api
 * This is a API document for Stylens Service
 *
 * OpenAPI spec version: 0.0.2
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BoxObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BoxObject'));
  } else {
    // Browser globals (root is window)
    if (!root.StyleApi) {
      root.StyleApi = {};
    }
    root.StyleApi.GetObjectsResponseData = factory(root.StyleApi.ApiClient, root.StyleApi.BoxObject);
  }
}(this, function(ApiClient, BoxObject) {
  'use strict';




  /**
   * The GetObjectsResponseData model module.
   * @module model/GetObjectsResponseData
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>GetObjectsResponseData</code>.
   * @alias module:model/GetObjectsResponseData
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>GetObjectsResponseData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetObjectsResponseData} obj Optional instance to populate.
   * @return {module:model/GetObjectsResponseData} The populated <code>GetObjectsResponseData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('boxes')) {
        obj['boxes'] = ApiClient.convertToType(data['boxes'], [BoxObject]);
      }
      if (data.hasOwnProperty('image_id')) {
        obj['image_id'] = ApiClient.convertToType(data['image_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/BoxObject>} boxes
   */
  exports.prototype['boxes'] = undefined;
  /**
   * @member {String} image_id
   */
  exports.prototype['image_id'] = undefined;



  return exports;
}));


