/**
 * style-api
 * This is a API document for Stylens Service
 *
 * OpenAPI spec version: 0.0.2
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StyleApi) {
      root.StyleApi = {};
    }
    root.StyleApi.SimImage = factory(root.StyleApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SimImage model module.
   * @module model/SimImage
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>SimImage</code>.
   * @alias module:model/SimImage
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>SimImage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimImage} obj Optional instance to populate.
   * @return {module:model/SimImage} The populated <code>SimImage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('product_name')) {
        obj['product_name'] = ApiClient.convertToType(data['product_name'], 'String');
      }
      if (data.hasOwnProperty('product_id')) {
        obj['product_id'] = ApiClient.convertToType(data['product_id'], 'String');
      }
      if (data.hasOwnProperty('host_code')) {
        obj['host_code'] = ApiClient.convertToType(data['host_code'], 'String');
      }
      if (data.hasOwnProperty('host_url')) {
        obj['host_url'] = ApiClient.convertToType(data['host_url'], 'String');
      }
      if (data.hasOwnProperty('host_name')) {
        obj['host_name'] = ApiClient.convertToType(data['host_name'], 'String');
      }
      if (data.hasOwnProperty('class_code')) {
        obj['class_code'] = ApiClient.convertToType(data['class_code'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('currency_unit')) {
        obj['currency_unit'] = ApiClient.convertToType(data['currency_unit'], 'String');
      }
      if (data.hasOwnProperty('product_url')) {
        obj['product_url'] = ApiClient.convertToType(data['product_url'], 'String');
      }
      if (data.hasOwnProperty('product_no')) {
        obj['product_no'] = ApiClient.convertToType(data['product_no'], 'String');
      }
      if (data.hasOwnProperty('nation')) {
        obj['nation'] = ApiClient.convertToType(data['nation'], 'String');
      }
      if (data.hasOwnProperty('main_image_mobile_full')) {
        obj['main_image_mobile_full'] = ApiClient.convertToType(data['main_image_mobile_full'], 'String');
      }
      if (data.hasOwnProperty('main_image_mobile_thumb')) {
        obj['main_image_mobile_thumb'] = ApiClient.convertToType(data['main_image_mobile_thumb'], 'String');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} product_name
   */
  exports.prototype['product_name'] = undefined;
  /**
   * @member {String} product_id
   */
  exports.prototype['product_id'] = undefined;
  /**
   * @member {String} host_code
   */
  exports.prototype['host_code'] = undefined;
  /**
   * @member {String} host_url
   */
  exports.prototype['host_url'] = undefined;
  /**
   * @member {String} host_name
   */
  exports.prototype['host_name'] = undefined;
  /**
   * @member {String} class_code
   */
  exports.prototype['class_code'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {String} currency_unit
   */
  exports.prototype['currency_unit'] = undefined;
  /**
   * @member {String} product_url
   */
  exports.prototype['product_url'] = undefined;
  /**
   * @member {String} product_no
   */
  exports.prototype['product_no'] = undefined;
  /**
   * @member {String} nation
   */
  exports.prototype['nation'] = undefined;
  /**
   * Mobile full size of image url
   * @member {String} main_image_mobile_full
   */
  exports.prototype['main_image_mobile_full'] = undefined;
  /**
   * Mobile thumbnail size of image url
   * @member {String} main_image_mobile_thumb
   */
  exports.prototype['main_image_mobile_thumb'] = undefined;
  /**
   * @member {String} version
   */
  exports.prototype['version'] = undefined;



  return exports;
}));


